status = warn
name = ExecutorLogConfig

appender.executor.type = File
appender.executor.name = ExecutorFile
appender.executor.fileName = logs/executor/spark-executor.log
appender.executor.layout.type = PatternLayout
appender.executor.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.executor.append = true

rootLogger.level = info
rootLogger.appenderRefs = executor
rootLogger.appenderRef.executor.ref = ExecutorFile

