status = warn
name = DriverLogConfig

appender.driver.type = File
appender.driver.name = DriverFile
appender.driver.fileName = logs/driver/spark-driver.log
appender.driver.layout.type = PatternLayout
appender.driver.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.driver.append = true

rootLogger.level = info
rootLogger.appenderRefs = driver
rootLogger.appenderRef.driver.ref = DriverFile

