spark.master                          local[*]
spark.submit.deployMode               client
spark.sql.session.timeZone            UTC
spark.hadoop.fs.s3a.impl              org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider com.amazonaws.auth.DefaultAWSCredentialsProviderChain
spark.hadoop.fs.s3a.path.style.access false

